#!/usr/bin/env python3
"""Emit a PyTorch nn.Module (.py) that rebuilds a Lancius v2 inference graph.

Same inference subset + fail-loud contract as export_lancius_onnx.py.
Weighted INPUTs become nn.Parameters (dequantized for INT8, downcast for
FP64 with a warning comment). Forward order follows file (topological) order.

Usage:
  python3 export_lancius_pytorch.py in.lancius out_model.py [--onnx out.onnx]

With --onnx, also traces the emitted module with a ones dummy input shaped
like the first weightless INPUT and exports ONNX (opset 17) for parity.
"""
import struct
import sys
import zlib
import numpy as np

from export_lancius_onnx import parse_lancius, lancius_shape, OP_NAMES

HEADER = '''"""Generated by Lancius export_lancius_pytorch.py — review before use."""
import torch
import torch.nn as nn
import torch.nn.functional as F


class LanciusModel(nn.Module):
    def __init__(self):
        super().__init__()
'''


def _w_f32(n):
    w = n['weights']
    if n['dtype'] == 0:
        return w.astype(np.float32)
    if n['dtype'] == 1:
        return (w.astype(np.float32) * float(n['scale']))
    if n['dtype'] == 2:
        return w.astype(np.float32)
    raise ValueError(f"node {n['id']}: INT32 weights not exportable")


def emit_module(parsed):
    nodes = parsed['nodes']
    by_id = {n['id']: n for n in nodes}
    lines_init = []
    lines_fwd = []
    params = {}   # lid -> (attr_name, shape)
    graph_inputs = [n for n in nodes if n['op'] == 1 and not n['has_w']]
    if not graph_inputs:
        raise ValueError("no weightless INPUT (graph input) found")
    primary = graph_inputs[0]

    for n in nodes:
        op, nid = n['op'], n['id']
        if op == 1 and n['has_w']:
            shp = lancius_shape(n)
            arr = _w_f32(n).reshape(shp)
            lines_init.append(
                f"        self.p{nid} = nn.Parameter(torch.tensor({arr.ravel().tolist()!r}, "
                f"dtype=torch.float32).reshape({shp}), requires_grad=False)")
            params[nid] = (f"self.p{nid}", shp)
        elif op == 2:
            shp = lancius_shape(n)
            v = float(n['attr'])
            lines_init.append(
                f"        self.p{nid} = nn.Parameter(torch.full({shp}, {v!r}, dtype=torch.float32), requires_grad=False)")
            params[nid] = (f"self.p{nid}", shp)

    def T(lid):
        return f"t{lid}"

    # Forward signature: one arg per graph input
    arg_names = [f"x{gi['id']}" for gi in graph_inputs]
    lines_fwd.append(f"    def forward(self, {', '.join(arg_names)}):")
    for gi, an in zip(graph_inputs, arg_names):
        lines_fwd.append(f"        {T(gi['id'])} = {an}.float()")

    for n in nodes:
        op, nid = n['op'], n['id']
        o = T(nid)
        if op in (0, 1, 2):
            if op == 1 and nid in params:
                lines_fwd.append(f"        {o} = {params[nid][0]}")
            elif op == 2 and nid in params:
                lines_fwd.append(f"        {o} = {params[nid][0]}")
            elif op == 0:
                pass
            continue
        ins = [T(i) for i in n['inputs']]
        if op == 3:
            lines_fwd.append(f"        {o} = {ins[0]} + {ins[1]}")
        elif op == 4:
            lines_fwd.append(f"        {o} = {ins[0]} - {ins[1]}")
        elif op == 5:
            lines_fwd.append(f"        {o} = {ins[0]} * {ins[1]}")
        elif op == 6:
            lines_fwd.append(f"        {o} = {ins[0]} @ {ins[1]}")
        elif op == 7:
            lines_fwd.append(f"        {o} = F.relu({ins[0]})")
        elif op == 38:
            lines_fwd.append(f"        {o} = torch.tanh({ins[0]})")
        elif op == 8:
            lines_fwd.append(f"        {o} = F.softmax({ins[0]}, dim=1)")
        elif op == 9:
            lines_fwd.append(f"        {o} = {ins[0]}.sum().reshape(1, 1)")
        elif op == 14:
            lines_fwd.append(f"        {o} = {ins[0]}.sum(dim=0, keepdim=True)")
        elif op == 15:
            lines_fwd.append(f"        {o} = {ins[0]}.sum(dim=1, keepdim=True)")
        elif op == 11:
            lines_fwd.append(f"        {o} = {ins[0]}.t()")
        elif op == 22:
            perm = [int(a) for a in n['axes'][:n['ndim']]]
            lines_fwd.append(f"        {o} = {ins[0]}.permute({perm})")
        elif op == 18:
            lines_fwd.append(f"        {o} = {ins[0]}.flatten(start_dim=1)")
        elif op == 27:
            shp = lancius_shape(n)
            lines_fwd.append(f"        {o} = {ins[0]}.reshape({shp})")
        elif op == 10:
            shp = lancius_shape(n)
            lines_fwd.append(f"        {o} = {ins[0]}.expand({shp})")
        elif op == 16:
            kh, kw, s, p = (int(x) for x in n['meta'])
            lines_fwd.append(f"        {o} = F.conv2d({ins[0]}, {T(n['inputs'][1])}, stride={s}, padding={p})"
                             if len(ins) >= 2 else
                             f"        {o} = F.conv2d({ins[0]}, {params[n['inputs'][1]][0]}, stride={s}, padding={p})")
            _ = (kh, kw)
        elif op == 17:
            kh, kw, s, _p = (int(x) for x in n['meta'])
            lines_fwd.append(f"        {o} = F.max_pool2d({ins[0]}, kernel_size={kh}, stride={s})")
        elif op == 40:
            lines_fwd.append(f"        {o} = ((_p := {ins[0]} - {ins[1]}) * _p).mean().reshape(1, 1)")
        else:
            nm = OP_NAMES.get(op, f"OP{op}")
            raise ValueError(f"lancius op {nm} (id {nid}) has no PyTorch mapping in this exporter.")

    out_node = None
    for n in nodes:
        if n['op'] == 20 and n['inputs']:
            out_node = by_id.get(n['inputs'][0])
            break
    if out_node is None:
        for n in reversed(nodes):
            if n['op'] not in (0, 1, 2):
                out_node = n
                break
    if out_node is None:
        raise ValueError("no computable output")
    lines_fwd.append(f"        return {T(out_node['id'])}")
    meta = (f"\n# LanciusMeta: nodes={len(nodes)} primary_input=t{primary['id']}{lancius_shape(primary)} "
            f"output=t{out_node['id']}{lancius_shape(out_node)}\n")
    src = HEADER + "\n".join("        # params" if False else l for l in lines_init) + "\n\n" + "\n".join(lines_fwd) + "\n" + meta
    # fix init block when no params
    if not lines_init:
        src = src.replace("    def __init__(self):\n        super().__init__()\n\n",
                          "    def __init__(self):\n        super().__init__()\n")
    return src, primary, out_node


def main():
    args = sys.argv[1:]
    if len(args) < 2:
        print(f"usage: {sys.argv[0]} in.lancius out_model.py [--onnx out.onnx]", file=sys.stderr)
        return 2
    in_p, out_py = args[0], args[1]
    onnx_out = None
    if '--onnx' in args:
        i = args.index('--onnx')
        if i + 1 >= len(args):
            print("FAIL: --onnx needs a path", file=sys.stderr)
            return 2
        onnx_out = args[i + 1]
    try:
        parsed = parse_lancius(in_p)
        src, primary, out_node = emit_module(parsed)
        with open(out_py, 'w') as f:
            f.write(src)
        print(f"OK: {len(parsed['nodes'])} lancius nodes -> {out_py} "
              f"(input t{primary['id']}{lancius_shape(primary)} output t{out_node['id']}{lancius_shape(out_node)})")
        if onnx_out:
            import torch
            import importlib.util
            spec = importlib.util.spec_from_file_location("lexp", out_py)
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            m = mod.LanciusModel().eval()
            shp = lancius_shape(primary)
            dummy = torch.ones(*shp)
            torch.onnx.export(m, dummy, onnx_out, input_names=['input'],
                              output_names=['output'], opset_version=17,
                              do_constant_folding=True)
            print(f"OK: traced ONNX -> {onnx_out}")
    except Exception as e:
        print(f"FAIL: {e}", file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
