#ifndef LANCIUS_VERSION_H
#define LANCIUS_VERSION_H

#define LANCIUS_VERSION_MAJOR 12
#define LANCIUS_VERSION_MINOR 0
#define LANCIUS_VERSION_PATCH 0
#define LANCIUS_VERSION_MILESTONE 1

#define LANCIUS_VERSION_PHASE "R1"
#define LANCIUS_VERSION_STRING "v12R1"

#endif
