#ifndef LANCIUS_VERSION_H
#define LANCIUS_VERSION_H

#define LANCIUS_VERSION_MAJOR 1
#define LANCIUS_VERSION_MINOR 2
#define LANCIUS_VERSION_PATCH 0
#define LANCIUS_VERSION_MILESTONE 12

#define LANCIUS_VERSION_PHASE "RC1"
#define LANCIUS_VERSION_STRING "v12R1"
#define LANCIUS_VERSION_PUBLIC "V1.2-RC1"

#endif
